### ISSUE TITLE
review redirect marketing/buy page to external browser

### ISSUE THREAD

**Issue by patte** [orbiting/app#116] opened 2018-07-31 20:15 UTC
On android it's possible to get to the marketing page inside the app. To reproduce, simply open the app and reload (pullDown) the signIn page.

![signal-attachment-2018-07-31-202134](https://user-images.githubusercontent.com/3500621/43484568-f6cbf9ec-950e-11e8-884c-6ddc7b3abc80.png)

**Comment by diegomura** [comment] 2018-08-01 16:34
Couldn't reproduce this issue. I tried everything: after installing, login in and out, everything. I only explanation for this happening is the app getting accidentally in some inconsistent state after logout. But again, couldn't get into that state

**Comment by patte** [comment] 2018-08-08 21:32
I just arrived on the purchase `/angebote` page in the iOS app. Steps to reproduce:
- signOut in app
- open an article in Safari, click on `Open` in the Republik App banner (the thing on top, with the App icon)
- The article opens in the app as it should. Now click on "Kommen Sie ebenfalls an Board" (link in the green advertisment)
- The purchase-page opens in the external browser. Now go back to the app, voilà there is also the purchase-page

Screenshots in order:
![image from ios](https://user-images.githubusercontent.com/3500621/43865586-4b0587bc-9b63-11e8-9e40-c2848f26b4c0.png)
![image from ios 1](https://user-images.githubusercontent.com/3500621/43865588-4e502dbe-9b63-11e8-82e9-d1aff66c6094.png)
![image from ios 2](https://user-images.githubusercontent.com/3500621/43865594-51345384-9b63-11e8-9b93-61d03dd977f3.png)

**Comment by diegomura** [comment] 2018-08-09 03:31
@patte this issue should be fixed.
I don't know if we should close this issue now, of if there's some other things to include inside here

**Comment by patte** [comment] 2018-08-09 11:43
@diegomura very nice! The problem above is solved, the app stays on the page where I clicked `/angebote`. Generally neither on android nor on iOS I found a way to reach `/angebote` or the marketing page. 👍 
There is a new problem tough, I think because of the fix you did. When I click on a link that should open in the external browser (but is not angebote) and I go back to the app, it's one step back, when it should have just stayed on the same page.
See the following gif: When going back to the app, I expect to still be on Andreas' profile page, not being set back to the team page.
![image from ios](https://user-images.githubusercontent.com/3500621/43896700-03e1358a-9bda-11e8-990d-4a2a9b44eda4.gif)

**Comment by diegomura** [comment] 2018-08-09 13:57
Damn. So we should go back only when that link is on the republik page? Odd. Fixing it now

**Comment by patte** [comment] 2018-08-09 14:48
@diegomura This doesn't make very much sense for me. Is it a race condition? If it's an internal link we have to go back because the client side navigation did already do it's job and for external links it takes longer?
Anyway when testing it on an iPhone it works as expected.

**Comment by diegomura** [comment] 2018-08-09 14:51
Yes. It's weird and unpredictable.
I don't think it's a race condition, but client vs server navigation. When server navigation, the [`stopLoading`](https://github.com/orbiting/app/blob/master/src/components/WebView.js#L141) call prevents the navigation. But that's not the case of client-side navigation. 
I'll try it on Android to be sure, and then if you agree close this issue

**Comment by patte** [comment] 2018-08-09 17:04
Would it not be possible to check the current url of the webview and based on that decide if it's necessary to go back or not?

**Comment by diegomura** [comment] 2018-08-09 17:59
That's what we are doing actually. When navigation change, we get the new webview url and decide to go back or not based on it

**Comment by diegomura** [comment] 2018-08-09 21:36
I think this can be closed

**Closed** 2018-08-24 14:01 UTC
Labels: high prio
